### PR TITLE
Update client.es.yml

### PR DESCRIPTION
**Pull request by SidVal**
Updated and translated new lines from client.en.yml

### CODE REVIEW

**Comment by fzngagan** [comment]
@SidVal Thanks for this. I'm looking into setting up Crowdin for automating the localization workflow. I'll push an update once that's in place.

**Comment by fzngagan** [comment]
@SidVal 
I'm thinking to merge this. Do you mind if we bring in these values later via crowdin?

**Comment by SidVal** [comment]
>Do you mind if we bring in these values later via crowdin?
Sure, crowdin its more slow for translations but if you prefer that, use it.

**Comment by fzngagan** [comment]
Looking good. Thanks @SidVal

**Pull request merged**
