### PR TITLE
Added rspec tests for QA

### PR DESCRIPTION
**Pull request by fzngagan**
Added tests for these classes

- DiscourseRatings::Cache
- DiscourseRatings::RatingType
- DiscourseRatings::Object
- DiscourseRatings::Rating
- PostsControllerRatingsExtension

### CODE REVIEW

**Comment by fzngagan** [comment]
current coverage 72.67%

**Comment by fzngagan** [comment]
current coverage 77.17%

**Comment by fzngagan** [comment]
Current coverage: 81.29%

**Comment by angusmcleod** [comment]
@fzngagan Is this ready for review?

**Comment by fzngagan** [comment]
> @fzngagan Is this ready for review?

Just one test that's failing. I'm looking at it today.

**Pull request merged**
